name: CI

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ 7.1, 7.2, 7.3, 7.4 ]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: tokenizer

      - run: make composer
      - run: make cs
      - run: make phpstan
      - run: make run-tests
